### ISSUE TITLE
Advanced filtering

### ISSUE THREAD

**Issue by WeTurkstra** [LYDIC-GROUP/rapid-api-crud-bundle#1]
Include advanced filtering. 

only question is should this be a seperate package?

**Comment by Rellix999** [comment]
Yes! Like we discussed, maybe you can set what kind of filter you want (none, simple by property, advanced) through bundle configuration. I would create a separate package and require it in this one. So when people want to use advanced filtering, they won't need this CRUD-focused package.

I'll plug your article here, since it's relevant and well written: https://willemturkstra.medium.com/the-doctrine-lexer-94ae215b3b05

**Comment by WeTurkstra** [comment]
Sure thing! I will create a seperate package for the filters. 

We should think about how to implement it in this bundle.
Define a set of interfaces for filtering to adapt to so we can use any odd package for filtering.
